# Generated by Django 4.1.4 on 2025-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Rent", "Rent"),
                            ("Transport", "Transport"),
                            ("Entertainment", "Entertainment"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
